# This is a basic workflow to help you get started with Actions

name: CLA

on:
  pull_request_target:
    types: [opened, edited, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup SSH Keys and known_hosts
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        ssh-agent -a $SSH_AUTH_SOCK > /dev/null
        ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"

    - name: Checkout CLA
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: git clone git@github.com:havogt/test_cla_file.git
    
    - name: Check for signed CLA
      run: cat test_cla_file/CLA_SIGNED | grep ${{ github.actor }}
