# This is a basic workflow to help you get started with Actions

name: CLA

on:
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Checkout CLA
      run: git clone git@github.com:havogt/test_cla_file.git
      
